services:
  app:
    image: qamii-app:latest
    container_name: qamii-app
    restart: unless-stopped
    environment:
      MONGODB_URI: ${MONGODB_URI}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_MP_CLIENT_ID: ${NEXT_PUBLIC_MP_CLIENT_ID}
      MP_CLIENT_SECRET: ${MP_CLIENT_SECRET}
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      APP_URL: ${APP_URL}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      R2_BUCKET_NAME: ${R2_BUCKET_NAME}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_SENDER: ${MAIL_SENDER}
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
